# Generated by Django 3.2 on 2021-12-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0002_auto_20211221_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
